projects:
  amanzada:
    schemaPath: amplify/backend/api/amanzada/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: eu-west-3
        apiId: null
        maxDepth: 3
